
services:
  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kitchen-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - kitchen-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/orders"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kitchen-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - kitchen-network
    restart: unless-stopped

networks:
  kitchen-network:
    driver: bridge
